"""Strategy Lab backtest bridge — uses the original AStockPursue backtest engine.

Unlike the Indicator Lab (which sandboxes user code against a single DataFrame),
the Strategy Lab writes a full SignalEngine class and runs it through the
existing backtest runner infrastructure. This supports:
- Multi-symbol, portfolio-level backtest
- All market engines (crypto, A-share, US equity, futures, forex)
- Risk parity / mean-variance optimizers
- Full metrics, equity curve, and trade log
"""

from __future__ import annotations

import importlib.util
import json
import logging
import sys
import tempfile
import uuid
from pathlib import Path
from typing import Any

import pandas as pd

logger = logging.getLogger(__name__)

_VALID_INTERVALS = {"1m", "5m", "15m", "30m", "1H", "4H", "1D", "1W", "4W"}

DEFAULT_SIGNAL_ENGINE_TEMPLATE = '''"""
Multi-factor signal engine — generated by Strategy Lab.

Contract:
  class SignalEngine:
      def generate(self, data_map: dict[str, pd.DataFrame]) -> dict[str, pd.Series]:
          ...
          return signal_map  # values in [-1, 1], positive=long, negative=short

data_map keys are symbol codes, values are OHLCV DataFrames with columns:
open, high, low, close, volume. Index is DatetimeIndex named "trade_date".
"""

import pandas as pd
import numpy as np
from typing import Dict


class SignalEngine:
    """Cross-sectional momentum strategy."""

    def generate(self, data_map: Dict[str, pd.DataFrame]) -> Dict[str, pd.Series]:
        signal_map: Dict[str, pd.Series] = {}

        # Compute momentum score for each symbol
        scores: Dict[str, float] = {}
        for code, df in data_map.items():
            if len(df) < 20:
                continue
            returns = df["close"].pct_change(5).iloc[-1]
            scores[code] = returns

        if not scores:
            return signal_map

        # Rank symbols by momentum, long top 30%, short bottom 30%
        ranked = sorted(scores.items(), key=lambda x: x[1])
        n = len(ranked)
        top_n = max(1, n // 3)
        bottom_n = max(1, n // 3)

        for i, (code, _) in enumerate(ranked):
            df = data_map[code]
            signal = pd.Series(0.0, index=df.index)
            if i >= n - top_n:
                signal.iloc[-1] = 1.0 / top_n   # long, equal weight
            elif i < bottom_n:
                signal.iloc[-1] = -1.0 / bottom_n  # short, equal weight
            signal_map[code] = signal

        return signal_map
'''


def run_strategy_backtest(
    code: str,
    codes: list[str],
    start_date: str = "2024-01-01",
    end_date: str = "2025-12-31",
    source: str = "auto",
    interval: str = "1D",
    initial_cash: float = 1_000_000.0,
    leverage: float = 1.0,
    slippage: float | None = None,
    slippage_mode: str = "fixed",
    extra_fields: list[str] | None = None,
    benchmark: str | None = "auto",
) -> dict[str, Any]:
    """Run a full backtest using the original AStockPursue engine.

    Args:
        code: Python source containing a ``SignalEngine`` class.
        codes: List of instrument codes (e.g. ["600519.SH", "000001.SZ"]).
        start_date: ISO date string.
        end_date: ISO date string.
        source: Data source ("auto", "yfinance", "tushare", etc.).
        interval: Bar interval.
        initial_cash: Starting capital.
        leverage: Leverage multiplier.
        extra_fields: Extra fundamental fields from daily_basic.

    Returns:
        dict with success, error, metrics, equity_curve, trades.
    """
    if interval not in _VALID_INTERVALS:
        return {"success": False, "error": f"Invalid interval: {interval}"}

    # 1. Create official run_dir under backend/runs/
    import time as _time
    RUNS_DIR = Path(__file__).resolve().parents[2] / "runs"
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    run_id = f"{_time.strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:8]}"
    run_dir = RUNS_DIR / run_id
    code_dir = run_dir / "code"
    code_dir.mkdir(parents=True, exist_ok=True)

    config = {
        "codes": codes,
        "start_date": start_date,
        "end_date": end_date,
        "source": source,
        "interval": interval,
        "initial_cash": initial_cash,
        "leverage": leverage,
        "engine": "daily",
        "benchmark": benchmark,
        "slippage": slippage,
        "slippage_mode": slippage_mode,
    }
    if extra_fields:
        config["extra_fields"] = extra_fields

    (run_dir / "config.json").write_text(json.dumps(config, indent=2))
    (code_dir / "signal_engine.py").write_text(code, encoding="utf-8")
    (run_dir / "state.json").write_text(json.dumps({"status": "success"}))
    (run_dir / "req.json").write_text(json.dumps({"prompt": f"Strategy Lab backtest: {', '.join(codes[:3])}", "source": source, "interval": interval}))

    # 2. Load signal engine and validate config
    from backtest.runner import (
        BacktestConfigSchema,
        _load_module_from_file,
    )
    from backtest.loaders.registry import (
        FALLBACK_CHAINS,
        LOADER_REGISTRY,
        _ensure_registered,
    )
    from backtest.loaders.base import NoAvailableSourceError
    from backtest.engines._market_hooks import _detect_market

    _ensure_registered()

    try:
        BacktestConfigSchema(**config)
    except Exception as e:
        return {"success": False, "error": f"Invalid config: {e}"}

    try:
        signal_module = _load_module_from_file(code_dir / "signal_engine.py", "signal_engine")
        engine_cls = getattr(signal_module, "SignalEngine", None)
        if engine_cls is None:
            return {"success": False, "error": "SignalEngine class not found in code"}
        signal_engine = engine_cls()
    except Exception as e:
        return {"success": False, "error": f"Failed to load SignalEngine: {e}"}

    # 3. Fetch data
    if source == "auto":
        from backtest.runner import _fetch_auto
        try:
            data_map = _fetch_auto(codes, config, interval)
        except Exception as e:
            return {"success": False, "error": f"Auto data fetch failed: {e}"}
    else:
        LoaderCls = LOADER_REGISTRY.get(source)
        if LoaderCls is None:
            return {"success": False, "error": f"Unknown source: {source}"}
        loader = LoaderCls()
        if hasattr(loader, "is_available") and not loader.is_available():
            return {"success": False, "error": f"Source {source} is not available"}
        try:
            data_map = loader.fetch(codes, start_date, end_date, interval=interval)
        except NoAvailableSourceError:
            data_map = {}
        except Exception as e:
            return {"success": False, "error": "Data fetch failed (%s): %s" % (source, e)}

        if not data_map and codes:
            market = _detect_market(codes[0])
            for fb_name in FALLBACK_CHAINS.get(market, []):
                if fb_name == source or fb_name not in LOADER_REGISTRY:
                    continue
                try:
                    fb_loader = LOADER_REGISTRY[fb_name]()
                    if hasattr(fb_loader, "is_available") and not fb_loader.is_available():
                        continue
                    data_map = fb_loader.fetch(codes, start_date, end_date, interval=interval)
                    if data_map:
                        source = fb_name
                        break
                except Exception:
                    continue

    # Survivorship-bias check
    missing_codes = [c for c in codes if c not in data_map or len(data_map.get(c, [])) == 0]
    if missing_codes:
        msg = f"{len(missing_codes)} symbol(s) have no data (delisted / inactive): {', '.join(missing_codes[:5])}"
        logger.warning("Survivorship bias: %s", msg)
        config.setdefault("_warnings", []).append(msg)
        codes = [c for c in codes if c not in missing_codes]
        config["codes"] = codes
        data_map = {k: v for k, v in data_map.items() if k not in missing_codes}

    if not data_map:
        return {"success": False, "error": f"No data fetched for {codes} (source={source})"}

    # 4. Create engine and run backtest
    from backtest.runner import _AutoLoader, _create_market_engine

    try:
        engine = _create_market_engine(source, config, list(data_map.keys()))
        auto_loader = _AutoLoader(data_map)
        from backtest.metrics import calc_bars_per_year
        bars_per_year = calc_bars_per_year(interval, source)
        metrics = engine.run_backtest(
            config=config,
            loader=auto_loader,
            signal_engine=signal_engine,
            run_dir=run_dir,
            bars_per_year=bars_per_year,
        )
    except Exception as e:
        logger.exception("Strategy backtest engine failed")
        (run_dir / "state.json").write_text(json.dumps({"status": "failed", "error": str(e)}))
        return {"success": False, "error": f"Backtest engine failed: {e}", "run_id": run_id}

    # 5. Persist metadata to PG
    try:
        from src.db.backtest_store import save_backtest_result
        summary = {
            "total_return": float(metrics.get("total_return", 0)),
            "sharpe": float(metrics.get("sharpe_ratio", 0)),
            "max_drawdown": float(metrics.get("max_drawdown", 0)),
            "win_rate": float(metrics.get("win_rate", 0)),
            "trade_count": int(metrics.get("trade_count", 0)),
            "profit_factor": float(metrics.get("profit_factor", 0)),
        }
        save_backtest_result(
            run_name=f"SLab: {', '.join(codes[:3])}",
            run_type="strategy",
            config={"codes": codes, "source": source, "interval": interval},
            metrics=summary,
            status="success",
        )
    except Exception:
        logger.debug("Failed to persist backtest to PG", exc_info=True)

    return {"success": True, "error": None, "run_id": run_id}


def _estimate_bars_per_year(interval: str) -> int:
    mapping = {"1m": 1440 * 365, "5m": 288 * 365, "15m": 96 * 365,
               "30m": 48 * 365, "1H": 24 * 365, "4H": 6 * 365, "1D": 365,
               "1W": 52, "4W": 13}
    return mapping.get(interval, 365)
