"""Daily factor signal brief generator.

Computes cross-sectional IC for all active factors on HS300/ZZ500
constituents, selects Top 5 by absolute IC, and renders a Markdown report.
"""

from __future__ import annotations

import logging
from datetime import date
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


class SignalBriefGenerator:
    """Generates daily factor signal brief with top IC factors."""

    def __init__(self, factor_service=None, market_data_provider=None):
        self.factor_service = factor_service
        self.market_data = market_data_provider

    def compute_cross_sectional_ic(
        self,
        factor_values: Dict[str, pd.DataFrame],
        forward_returns: pd.DataFrame,
    ) -> pd.Series:
        """Compute cross-sectional IC for each factor.

        For each factor, computes the mean cross-sectional Pearson
        correlation between factor values and forward returns, using
        ``corrwith(axis=1)`` similar to ``factors.mining.fitness.ic_fitness``.

        Args:
            factor_values: Dict mapping factor_name → DataFrame (dates × stocks).
            forward_returns: DataFrame (dates × stocks) with forward returns
                aligned to factor dates.

        Returns:
            Series of mean IC values indexed by factor name.
        """
        ics: Dict[str, float] = {}
        for factor_name, fv in factor_values.items():
            if fv.empty or forward_returns.empty:
                ics[factor_name] = 0.0
                continue

            # Align on dates and columns (stocks)
            common_dates = fv.index.intersection(forward_returns.index)
            common_cols = fv.columns.intersection(forward_returns.columns)

            if len(common_dates) < 3 or len(common_cols) < 3:
                ics[factor_name] = 0.0
                continue

            fv_aligned = fv.loc[common_dates, common_cols]
            fr_aligned = forward_returns.loc[common_dates, common_cols]

            ic_series = fv_aligned.corrwith(
                fr_aligned, axis=1, method="pearson", min_periods=3
            ).dropna()
            ics[factor_name] = float(ic_series.mean()) if len(ic_series) > 0 else 0.0

        return pd.Series(ics)

    def select_top_factors(
        self, ics: pd.Series, n: int = 5
    ) -> List[Tuple[str, float]]:
        """Select top N factors by absolute IC value.

        Args:
            ics: Series of IC values indexed by factor name.
            n: Number of top factors to return.

        Returns:
            List of (factor_name, ic_value) tuples sorted by abs(IC) desc.
        """
        abs_ics = ics.abs().sort_values(ascending=False)
        top = abs_ics.head(n)
        return [(name, float(ics[name])) for name in top.index]

    def compute_daily_factors(
        self, target_date: date, universe: str = "HS300"
    ) -> Dict[str, pd.DataFrame]:
        """Compute all active factor values for the given universe on
        *target_date*.

        Delegates to *factor_service* when available; returns an empty
        dict otherwise.
        """
        if self.factor_service:
            return self.factor_service.compute_all(target_date, universe)
        logger.warning("No factor_service configured, returning empty dict")
        return {}

    def render_markdown(
        self,
        top_factors: List[Tuple[str, float]],
        signals: Optional[Dict[str, List[str]]] = None,
        target_date: Optional[date] = None,
    ) -> str:
        """Render Markdown signal brief.

        Args:
            top_factors: List of (factor_name, ic_value) tuples.
            signals: Optional dict of factor_name → list of stock symbols
                with signals.
            target_date: Date for the report header.

        Returns:
            Markdown string.
        """
        date_str = target_date.strftime("%Y-%m-%d") if target_date else "today"
        lines = [
            f"\U0001f4ca AStockPursue 每日信号 — {date_str}",
            "",
            "今日最强因子（截面 IC Top 5）：",
        ]
        for i, (name, ic) in enumerate(top_factors, 1):
            direction = "看多" if ic > 0 else "看空"
            stock_list = ""
            if signals and name in signals:
                stock_list = "  " + ", ".join(signals[name])
            lines.append(
                f"{i}. {name:<16} IC={ic:+.3f}  {direction}{stock_list}"
            )

        lines.extend(
            [
                "",
                "---",
                "*Automatically generated by AStockPursue Signal Engine*",
            ]
        )
        return "\n".join(lines)
