"""Report generation — export backtest results as PDF reports.

Uses weasyprint (HTML → PDF) with a Jinja2 template. Falls back to
plain-text summary if weasyprint is not installed.

Usage::

    from backtest.report import generate_pdf_report

    pdf_bytes = generate_pdf_report(run_dir, metrics, trades, equity_df)
    with open("report.pdf", "wb") as f:
        f.write(pdf_bytes)
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8">
<style>
  body { font-family: 'Segoe UI', 'Noto Sans SC', sans-serif; max-width: 800px; margin: 40px auto; color: #222; }
  h1 { border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
  h2 { color: #2563eb; margin-top: 24px; }
  .metrics { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0; }
  .metric { background: #f8fafc; border-radius: 8px; padding: 12px; text-align: center; }
  .metric .value { font-size: 22px; font-weight: 700; color: #2563eb; }
  .metric .label { font-size: 12px; color: #64748b; margin-top: 4px; }
  .positive { color: #16a34a; } .negative { color: #dc2626; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
  th { background: #f1f5f9; text-align: left; padding: 8px; border-bottom: 2px solid #e2e8f0; }
  td { padding: 6px 8px; border-bottom: 1px solid #f1f5f9; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
  pre { background: #f8fafc; border-radius: 6px; padding: 12px; font-size: 12px; overflow-x: auto; }
</style>
</head>
<body>
<h1>AStockPursue — Backtest Report</h1>
<p>Generated: {{ generated_at }}</p>
<p>Run: {{ run_id }}</p>
<p>Symbols: {{ symbols }}</p>
<p>Period: {{ start_date }} → {{ end_date }}</p>

<h2>Performance Metrics</h2>
<div class="metrics">
  <div class="metric"><div class="value {{ total_return_class }}">{{ total_return }}</div><div class="label">Total Return</div></div>
  <div class="metric"><div class="value">{{ sharpe }}</div><div class="label">Sharpe Ratio</div></div>
  <div class="metric"><div class="value {{ max_dd_class }}">{{ max_drawdown }}</div><div class="label">Max Drawdown</div></div>
  <div class="metric"><div class="value">{{ win_rate }}</div><div class="label">Win Rate</div></div>
  <div class="metric"><div class="value">{{ annual_return }}</div><div class="label">Annual Return</div></div>
  <div class="metric"><div class="value">{{ calmar }}</div><div class="label">Calmar Ratio</div></div>
  <div class="metric"><div class="value">{{ trade_count }}</div><div class="label">Trades</div></div>
  <div class="metric"><div class="value">{{ profit_factor }}</div><div class="label">Profit Factor</div></div>
</div>

<h2>Trade Summary</h2>
<table>
<tr><th>Symbol</th><th>Trades</th><th>Win Rate</th><th>Total PnL</th></tr>
{% for s in by_symbol %}
<tr><td>{{ s.symbol }}</td><td>{{ s.trades }}</td><td>{{ s.win_rate }}</td><td class="{{ s.pnl_class }}">{{ s.pnl }}</td></tr>
{% endfor %}
</table>

{% if trades %}
<h2>Recent Trades</h2>
<table>
<tr><th>Symbol</th><th>Entry</th><th>Exit</th><th>PnL</th><th>Reason</th></tr>
{% for t in trades[:30] %}
<tr>
  <td>{{ t.symbol }}</td>
  <td>{{ t.entry }}</td>
  <td>{{ t.exit }}</td>
  <td class="{{ t.pnl_class }}">{{ t.pnl }}</td>
  <td>{{ t.reason }}</td>
</tr>
{% endfor %}
</table>
{% endif %}

{% if risk_metrics %}
<h2>Risk Metrics</h2>
<div class="metrics">
  {% for r in risk_metrics %}
  <div class="metric"><div class="value">{{ r.value }}</div><div class="label">{{ r.label }}</div></div>
  {% endfor %}
</div>
{% endif %}

<div class="footer">Generated by AStockPursue · {{ generated_at }}</div>
</body>
</html>"""


def _build_report_html(
    run_id: str,
    symbols: str,
    start_date: str,
    end_date: str,
    metrics: dict[str, Any],
    trades: list[dict],
    risk_metrics: list[dict] | None = None,
) -> str:
    """Build HTML report from template."""
    total_ret = metrics.get("total_return", 0)
    max_dd = metrics.get("max_drawdown", 0)

    # Per-symbol summary
    by_symbol = metrics.get("by_symbol", [])
    for s in by_symbol:
        pnl = s.get("pnl", 0)
        s["pnl_class"] = "positive" if pnl > 0 else "negative" if pnl < 0 else ""
        wr = s.get("win_rate", 0)
        s["win_rate"] = f"{wr:.1%}" if wr else "N/A"
        s["pnl"] = f"{pnl:+,.2f}" if pnl else "0"

    # Recent trades formatting
    formatted_trades = []
    for t in (trades or [])[:30]:
        pnl = t.get("pnl", 0)
        formatted_trades.append({
            "symbol": t.get("symbol", ""),
            "entry": f"{t.get('entry_price', 0):.2f}",
            "exit": f"{t.get('exit_price', 0):.2f}",
            "pnl": f"{pnl:+,.2f}",
            "pnl_class": "positive" if pnl > 0 else "negative" if pnl < 0 else "",
            "reason": t.get("exit_reason", ""),
        })

    # Simple template substitution
    html = _REPORT_TEMPLATE
    html = html.replace("{{ generated_at }}", datetime.now().strftime("%Y-%m-%d %H:%M"))
    html = html.replace("{{ run_id }}", run_id)
    html = html.replace("{{ symbols }}", symbols)
    html = html.replace("{{ start_date }}", start_date)
    html = html.replace("{{ end_date }}", end_date)
    html = html.replace("{{ total_return }}", f"{total_ret:+.2%}")
    html = html.replace("{{ total_return_class }}", "positive" if total_ret > 0 else "negative")
    html = html.replace("{{ sharpe }}", f"{metrics.get('sharpe_ratio', 0):.2f}")
    html = html.replace("{{ max_drawdown }}", f"{max_dd:.2%}")
    html = html.replace("{{ max_dd_class }}", "negative" if max_dd < -0.1 else "")
    html = html.replace("{{ win_rate }}", f"{metrics.get('win_rate', 0):.1%}")
    html = html.replace("{{ annual_return }}", f"{metrics.get('annual_return', 0):+.2%}")
    html = html.replace("{{ calmar }}", f"{metrics.get('calmar_ratio', 0):.2f}")
    html = html.replace("{{ trade_count }}", str(metrics.get("trade_count", 0)))
    html = html.replace("{{ profit_factor }}", f"{metrics.get('profit_factor', 0):.2f}")

    # Build trade table rows
    trade_rows = ""
    for t in formatted_trades:
        trade_rows += f"<tr><td>{t['symbol']}</td><td>{t['entry']}</td><td>{t['exit']}</td><td class=\"{t['pnl_class']}\">{t['pnl']}</td><td>{t['reason']}</td></tr>\n"
    html = html.replace("{% for t in trades[:30] %}", "").replace("{% endfor %}", "")
    # Replace the template loop with actual rows
    import re
    html = re.sub(r'<tr>.*?{% for t in trades\[:30\] %}.*?</tr>\n.*?{% endfor %}', '', html, flags=re.DOTALL)
    # Instead, add trade rows before </tbody> equivalent — simpler to just append
    if trade_rows:
        html = html.replace("</table>", f"</table>\n{trade_rows}\n</table>", 1)

    # Symbol table rows
    sym_rows = ""
    for s in by_symbol:
        sym_rows += f"<tr><td>{s.get('symbol','')}</td><td>{s.get('trades',0)}</td><td>{s.get('win_rate','')}</td><td class=\"{s.get('pnl_class','')}\">{s.get('pnl','')}</td></tr>\n"
    html = re.sub(r'{% for s in by_symbol %}.*?{% endfor %}', sym_rows, html, flags=re.DOTALL)

    # Risk metrics
    if risk_metrics:
        risk_html = ""
        for r in risk_metrics:
            risk_html += f"<div class=\"metric\"><div class=\"value\">{r['value']}</div><div class=\"label\">{r['label']}</div></div>\n"
        html = re.sub(r'{% for r in risk_metrics %}.*?{% endfor %}', risk_html, html, flags=re.DOTALL)

    # Remove remaining template tags
    html = re.sub(r'{% if .*? %}', '', html)
    html = re.sub(r'{% endif %}', '', html)

    return html


def generate_pdf_report(
    run_dir: Path,
    metrics: dict[str, Any],
    trades: list[dict],
    risk_metrics: list[dict] | None = None,
) -> bytes:
    """Generate a PDF report for a backtest run.

    Args:
        run_dir: Path to the run directory.
        metrics: Dict from ``calc_metrics()``.
        trades: List of trade dicts.
        risk_metrics: Optional list of {label, value} risk metrics.

    Returns:
        PDF file as bytes.
    """
    config_path = run_dir / "config.json"
    config = {}
    if config_path.exists():
        try:
            config = json.loads(config_path.read_text())
        except Exception:
            pass

    run_id = run_dir.name
    symbols = ", ".join(config.get("codes", []))
    start_date = config.get("start_date", "")
    end_date = config.get("end_date", "")

    html = _build_report_html(
        run_id=run_id,
        symbols=symbols,
        start_date=start_date,
        end_date=end_date,
        metrics=metrics,
        trades=trades,
        risk_metrics=risk_metrics,
    )

    try:
        from weasyprint import HTML
        return HTML(string=html).write_pdf()
    except ImportError:
        logger.debug("weasyprint not installed — falling back to HTML")
        return html.encode("utf-8")


def generate_report_file(
    run_dir: Path,
    output_path: Path,
    metrics: dict[str, Any],
    trades: list[dict],
    risk_metrics: list[dict] | None = None,
) -> Path:
    """Generate report and save to *output_path*. Returns *output_path*."""
    pdf_bytes = generate_pdf_report(run_dir, metrics, trades, risk_metrics)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(pdf_bytes)
    logger.info("Report saved to %s", output_path)
    return output_path
