import { useCallback, useEffect, useState } from "react";
import { Code, Save, Trash2, Plus, BarChart3, Target } from "lucide-react";
import { cn } from "@/lib/utils";
import { useI18n } from "@/lib/i18n";
import { authHeaders } from "@/lib/apiAuth";
import { CodeEditor } from "@/components/indicator-lab/CodeEditor";
import { StrategyBacktestPanel } from "@/components/indicator-lab/StrategyBacktestPanel";

const API_BASE = "/strategy-lab";

async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> {
  const headers: Record<string, string> = { "Content-Type": "application/json", ...authHeaders() as Record<string, string> };
  const res = await fetch(`${API_BASE}${path}`, { ...options, headers: { ...headers, ...(options?.headers as Record<string, string> || {}) } });
  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error(body.detail || `HTTP ${res.status}`);
  }
  return res.json();
}

const DEFAULT_CODE = `"""
Multi-factor signal engine — generated by Strategy Lab.

Contract:
  class SignalEngine:
      def generate(self, data_map: dict[str, pd.DataFrame]) -> dict[str, pd.Series]:
          ...
          return signal_map  # values in [-1, 1], positive=long, negative=short

data_map keys are symbol codes, values are OHLCV DataFrames with columns:
open, high, low, close, volume. Index is DatetimeIndex named "trade_date".
"""

import pandas as pd
import numpy as np
from typing import Dict


class SignalEngine:
    """Cross-sectional momentum strategy."""

    def generate(self, data_map: Dict[str, pd.DataFrame]) -> Dict[str, pd.Series]:
        signal_map: Dict[str, pd.Series] = {}

        for code, df in data_map.items():
            if len(df) < 20:
                continue
            returns = df["close"].pct_change(5).iloc[-1]
            signal = pd.Series(0.0, index=df.index)
            if returns > 0:
                signal.iloc[-1] = 0.5   # long 50%
            else:
                signal.iloc[-1] = -0.5  # short 50%
            signal_map[code] = signal

        return signal_map
`;

interface StrategyInfo {
  id: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
}

export function StrategyLab() {
  const { t } = useI18n();
  const [code, setCode] = useState(DEFAULT_CODE);
  const [strategies, setStrategies] = useState<StrategyInfo[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [showBacktest, setShowBacktest] = useState(false);

  const loadList = useCallback(async () => {
    try {
      const data = await apiFetch<{ strategies: StrategyInfo[] }>("/list");
      setStrategies(data.strategies);
    } catch { /* ignore */ }
  }, []);

  useEffect(() => { loadList(); }, [loadList]);

  useEffect(() => {
    if (!selectedId) return;
    apiFetch<{ code: string }>(`/${selectedId}`)
      .then((data) => { setCode(data.code); setMessage(null); })
      .catch(() => setMessage("Failed to load strategy"));
  }, [selectedId]);

  const handleSave = async () => {
    setSaving(true);
    setMessage(null);
    try {
      const data = await apiFetch<StrategyInfo>("/save", {
        method: "POST",
        body: JSON.stringify({ code, strategy_id: selectedId || undefined }),
      });
      setSelectedId(data.id);
      setMessage(`Saved as "${data.name}"`);
      loadList();
    } catch (e) {
      setMessage(String(e));
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (id: string) => {
    try {
      await apiFetch(`/delete/${id}`, { method: "POST" });
      if (selectedId === id) setSelectedId(null);
      loadList();
      setMessage("Strategy deleted");
    } catch (e) { setMessage(String(e)); }
  };

  const handleNew = () => {
    setCode(DEFAULT_CODE);
    setSelectedId(null);
    setMessage(null);
  };

  return (
    <div className="flex h-[calc(100vh-3rem)]">
      <div className="flex-1 flex flex-col min-w-0">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-2 border-b bg-card shrink-0">
          <div className="flex items-center gap-2">
            <Target className="h-4 w-4 text-primary" />
            <h1 className="text-sm font-semibold">{t.strategyLab || "Strategy Lab"}</h1>
          </div>
          <div className="flex items-center gap-1.5">
            <button onClick={handleNew} className="flex items-center gap-1 px-2 py-1 text-xs rounded hover:bg-muted transition-colors" title={t.indicatorLabNewIndicator}>
              <Plus className="h-3 w-3" />
              {t.indicatorLabNew}
            </button>
            <button onClick={() => setShowBacktest(true)} className="flex items-center gap-1 px-2 py-1 text-xs rounded bg-success/10 text-success hover:bg-success/20 transition-colors">
              <BarChart3 className="h-3 w-3" />
              {t.indicatorLabBacktest}
            </button>
            <button onClick={handleSave} disabled={saving} className="flex items-center gap-1 px-2 py-1 text-xs rounded bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50">
              <Save className="h-3 w-3" />
              {saving ? t.indicatorLabSaving : t.indicatorLabSave}
            </button>
          </div>
        </div>

        {/* Message bar */}
        {message && (
          <div className={cn(
            "px-4 py-1.5 text-xs border-b shrink-0",
            message.includes("failed") || message.includes("error")
              ? "bg-danger/10 text-danger border-danger/20"
              : "bg-success/10 text-success border-success/20"
          )}>
            {message}
          </div>
        )}

        {/* Template hint */}
        <div className="px-4 py-2 text-xs text-muted-foreground bg-muted/30 border-b shrink-0">
          <strong>SignalEngine</strong> 合约：实现 <code className="bg-muted px-1 rounded text-[10px]">generate(self, data_map) -&gt; dict[str, pd.Series]</code>，返回值为持仓权重（正=做多，负=做空，范围 [-1, 1]）。支持多标的组合回测。
        </div>

        {/* Editor */}
        <div className="flex-1 p-4 min-h-0">
          <CodeEditor value={code} onChange={setCode} onSave={handleSave} />
        </div>
      </div>

      {/* Right sidebar — Strategy list */}
      <aside className="w-64 border-l bg-card flex flex-col shrink-0">
        <div className="flex items-center gap-1 px-3 py-2 border-b text-xs font-medium text-muted-foreground">
          <Code className="h-3 w-3" />
          {t.indicatorLabList}
        </div>
        <div className="flex-1 overflow-auto p-2 space-y-1">
          {strategies.length === 0 && (
            <p className="text-xs text-muted-foreground text-center py-8">
              {t.indicatorLabNoIndicators}
            </p>
          )}
          {strategies.map((s) => (
            <div key={s.id} className={cn(
              "flex items-center justify-between px-2 py-1.5 rounded text-xs cursor-pointer transition-colors group",
              selectedId === s.id ? "bg-primary/10 text-primary" : "hover:bg-muted text-muted-foreground hover:text-foreground"
            )} onClick={() => setSelectedId(s.id)}>
              <div className="min-w-0 flex-1">
                <div className="truncate font-medium">{s.name}</div>
                <div className="text-[10px] opacity-60">{s.created_at?.slice(0, 10)}</div>
              </div>
              <button onClick={(e) => { e.stopPropagation(); handleDelete(s.id); }} className="p-1 opacity-0 group-hover:opacity-100 text-muted-foreground hover:text-danger rounded transition-all" title="Delete">
                <Trash2 className="h-3 w-3" />
              </button>
            </div>
          ))}
        </div>
      </aside>

      {/* Backtest modal — reuse from Indicator Lab */}
      {showBacktest && (
        <StrategyBacktestPanel code={code} onClose={() => setShowBacktest(false)} />
      )}
    </div>
  );
}
